name: 'Destroy'

on: 
  workflow_dispatch:


jobs:
  terraform:
    name: 'Destroy Configuration'
    runs-on: ubuntu-latest

    steps:
    - name: Terraform destroy
      env:
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      run: terraform destroy -auto-approve -input=false