name: 'Destroy'

on: 
  workflow_dispatch:

env:
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}

jobs:

# Use the Bash shell regardless of whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
  defaults:
    run:
      shell: bash

  terraform:
    name: 'Destroy Configuration'
    runs-on: ubuntu-latest

    steps:
    # For destroy, checkout and init are necessary steps
    # Checkout client files first to runner's root
    - name: Checkout Client
      uses: actions/checkout@v3

    # Checkout the module repository separate folder protecting root files
    - name: Checkout Modules
      uses: actions/checkout@v3
      with:
        repository: WolfgangBaeck/REB3Modules
        path: modules

    # Install the preferred version of Terraform CLI 
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.1.7

    - name: Terraform Init
      run: terraform init

    - name: Terraform destroy
      run: terraform destroy -auto-approve