name: 'Destroy'

on: 
  workflow_dispatch:

env:
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}

jobs:

  terraform:
    name: 'Destroy Configuration'
    runs-on: ubuntu-latest
    # Use the Bash shell regardless of whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # For destroy, checkout and init are necessary steps
    # Checkout the module repository to root file system    
    - name: Checkout Modules
      uses: actions/checkout@v3
      with:
        repository: WolfgangBaeck/REB3Modules    
    - name: Show FileSystem 1
      run: ls -R
    # Checkout client files to separate folder protecting root
    - name: Checkout Client
      uses: actions/checkout@v3
      with:
        path: client
    - name: Show FileSystem 2
      run: ls -R

    # Install the preferred version of Terraform CLI 
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.1.7

    - name: Terraform Init
      run: terraform init

    - name: Terraform destroy
      run: terraform destroy -auto-approve